osx_image: xcode61
language: objective-c
before_script:
  - export LANG=en_US.UTF-8
script: xcodebuild -workspace Ello.xcworkspace -scheme Ello -sdk iphonesimulator clean test
branches:
  only:
  - master
notifications:
  email: false

# TODO: add s3 ipa archiving at some point