osx_image: xcode611
language: objective-c
rvm: 2.1.3
git:
  depth: 1
cache:
  directories:
  - vendor/bundle
  - Pods
install:
- bundle install
- bundle exec pod keys set ClientKey $ELLO_CLIENT_KEY Ello
- bundle exec pod keys set ClientSecret $ELLO_CLIENT_SECRET Ello
- bundle exec pod keys set Domain $ELLO_DOMAIN Ello
- bundle exec pod keys set Salt $ELLO_SALT Ello
- bundle exec pod install
before_script:
- export LANG=en_US.UTF-8
script: "./bin/travis-build.sh"
branches:
  only:
  - master
notifications:
  email: false
  slack:
    secure: ZikJQt/R40LMj27fu2ub9Zq87FF6kZXx3fXy9lz/nWFuc7EWcQC8SzVOCizSp+cq/wrsyBPfitkQwVsFpxx/6aJC0r+t4/zIwK21aLIkkHYLzS5qJpifYeTp7kAiQ0eFWLNLxRSwDVEMlfcvgHl7kGmvJQkzHm9mkQaWBJAJayc=
env:
  secure: TzBIvRqXHf4sB4NNrox108gYrq/AUNYOzbv0MMJ1g65IZiAU4F4hEV4k56esME5tbN6+/smbAQYUQOB1Oy1Y0sRmjM3yx3hkmR9dtlakROslbswiHHFsaVeCm4/qlXB5TEDe/dWwpnV+15HZmtnXIAo9tOejQ8qgDI3avL2cgp4=
