osx_image: xcode611
language: objective-c
rvm: 2.1.3
cache:
  directories:
    - vendor/bundle
    - Pods
install:
  - bundle install
  - bundle exec pod install
before_script:
  - export LANG=en_US.UTF-8
script: ./bin/travis-build.sh
branches:
  only:
    - master
notifications:
  email: false
  slack:
    secure: ZikJQt/R40LMj27fu2ub9Zq87FF6kZXx3fXy9lz/nWFuc7EWcQC8SzVOCizSp+cq/wrsyBPfitkQwVsFpxx/6aJC0r+t4/zIwK21aLIkkHYLzS5qJpifYeTp7kAiQ0eFWLNLxRSwDVEMlfcvgHl7kGmvJQkzHm9mkQaWBJAJayc=

# TODO: add s3 ipa archiving at some point
