osx_image: xcode61
language: objective-c
before_script:
  - export LANG=en_US.UTF-8
script: ./travis-build.sh
branches:
  only:
  - master
notifications:
  email: false
  slack:
    secure: ZikJQt/R40LMj27fu2ub9Zq87FF6kZXx3fXy9lz/nWFuc7EWcQC8SzVOCizSp+cq/wrsyBPfitkQwVsFpxx/6aJC0r+t4/zIwK21aLIkkHYLzS5qJpifYeTp7kAiQ0eFWLNLxRSwDVEMlfcvgHl7kGmvJQkzHm9mkQaWBJAJayc=

# TODO: add s3 ipa archiving at some point
