language: objective-c
xcode_workspace: Ello.xcworkspace
xcode_scheme: Ello
xcode_sdk: iphonesimulator10.3
git:
  depth: 1
cache:
- bundler
- cocoapods
before_install:
- export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 8 (11.4" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
- echo $IOS_SIMULATOR_UDID
install:
- gem install bundler
- bundle install
- bundle exec pod keys set OauthKey $ELLO_CLIENT_KEY Ello
- bundle exec pod keys set OauthSecret $ELLO_CLIENT_SECRET Ello
- bundle exec pod keys set Domain $ELLO_DOMAIN Ello
- bundle exec pod keys set SodiumChloride $INVITE_FRIENDS_SALT Ello
- bundle exec pod keys set SegmentKey $ELLO_SEGMENT_KEY Ello
- bundle exec pod keys set TeamId ABC123 Ello
- bundle exec pod keys set StagingSegmentKey "any" Ello
- bundle exec pod keys set NinjaOauthKey "any" Ello
- bundle exec pod keys set NinjaOauthSecret "any" Ello
- bundle exec pod keys set NinjaDomain "any" Ello
- bundle exec pod keys set RainbowOauthKey "any" Ello
- bundle exec pod keys set RainbowOauthSecret "any" Ello
- bundle exec pod keys set RainbowDomain "any" Ello
- bundle exec pod keys set Stage1OauthKey "any" Ello
- bundle exec pod keys set Stage1OauthSecret "any" Ello
- bundle exec pod keys set Stage1Domain "any" Ello
- bundle exec pod keys set Stage2OauthKey "any" Ello
- bundle exec pod keys set Stage2OauthSecret "any" Ello
- bundle exec pod keys set Stage2Domain "any" Ello
- bundle exec pod repo update --silent
- bundle exec pod install --verbose
before_script:
- export LANG=en_US.UTF-8
script:
- xcodebuild -workspace Ello.xcworkspace -scheme Ello -sdk iphonesimulator11.4 -configuration Debug -destination "id=$IOS_SIMULATOR_UDID" build test | xcpretty -f `xcpretty-travis-formatter`
notifications:
  email: false
  slack:
    rooms:
      secure: "l9W6tZ8Ycy64hjGU0ZKqfRDPBibaPofHBANmqR+ZL82fyqmL+e8xo8SfYZ4WIzECmO/CmLHd2jO7Em5PGPv3PrsOciSnbHJRBv++ZC21ebtNSWZiyQeIMmeoNDv021i1Vz/P7jTTmsHeZuf5eKwo3N6+IuC216qw3kPWAta/XocVrpG7vxNFB/9sCP5ZFr7kiM9k7pMSGAwl63Sh+uzBkDWk3n+KRh7EM+yPGAfgsdx4Q+S/rQlHbiEOnEzEPNFLBe80NQ9TSzVN1CQ4iuZ4Ny9c2Wy3ZB3ppJrL0RF9iT4ePonA+prG5LS2gS5iEbMT5TT5OKvIAS0M6S7sYcdhPzy1McweDW0JFRv+BoXRRt3YFbo+ytpRB9fmpz5/ATE8PAnEpVKUox1jlMMg/nHQs9sSZRp1sfP8E+2Iky/om3d6bxhjY4fFbVe4M/VXTWHE81NIQbCTfkA/O3uJ8bxJGLa/Z80EhNDpJaEnZvpOWINlVay4CSV2BAaiJEZRwMqSlgdUJnSJUYJ7lWkeWJLySVKjsGOAcd5u258e/d5jkjOuVXuQyou9A4eVoB8zHoCkz98sZEBpg5zMYbYFewdx4/GM8lGOjjnrIvE+7u4czmX/LeqUbDeMrQl8R1Rh55s7EuiHQa/O/g6yhHO4KDQnJ/PF0v0LHJV6zzkTRlJ+L+k="
