osx_image: xcode8.3
language: objective-c
xcode_sdk: iphonesimulator10.3
git:
  depth: 1
cache:
- bundler
- cocoapods
before_install:
- export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 7 (10.3" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
- echo $IOS_SIMULATOR_UDID
- open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID
install:
- gem install bundler
- bundle install
- bundle exec pod keys set OauthKey $ELLO_CLIENT_KEY Ello
- bundle exec pod keys set OauthSecret $ELLO_CLIENT_SECRET Ello
- bundle exec pod keys set Domain $ELLO_DOMAIN Ello
- bundle exec pod keys set SodiumChloride $INVITE_FRIENDS_SALT Ello
- bundle exec pod keys set CrashlyticsKey $ELLO_CRASHLYTICS_KEY Ello
- bundle exec pod keys set SegmentKey $ELLO_SEGMENT_KEY Ello
- bundle exec pod keys set TeamId ABC123 Ello
- bundle exec pod keys set StagingSegmentKey "any" Ello
- bundle exec pod keys set NinjaOauthKey "any" Ello
- bundle exec pod keys set NinjaOauthSecret "any" Ello
- bundle exec pod keys set NinjaDomain "any" Ello
- bundle exec pod keys set Stage1OauthKey "any" Ello
- bundle exec pod keys set Stage1OauthSecret "any" Ello
- bundle exec pod keys set Stage1Domain "any" Ello
- bundle exec pod keys set Stage2OauthKey "any" Ello
- bundle exec pod keys set Stage2OauthSecret "any" Ello
- bundle exec pod keys set Stage2Domain "any" Ello
- bundle exec pod repo update --silent
- bundle exec pod install
before_script:
- export LANG=en_US.UTF-8
script:
- gem install danger -v 2.0.1 --no-ri --no-rdoc && danger
- set -o pipefail && xcodebuild -workspace Ello.xcworkspace -scheme Ello -configuration
  Debug -destination "id=$IOS_SIMULATOR_UDID" clean test | xcpretty -f `xcpretty-travis-formatter`
notifications:
  email: false
  slack:
    rooms:
      secure: Rew+SaUriW54jGxs1A5s0QX282QOjXLErm4E6uAMexbwJK5HePAU157rp+/EynEUttykYHIkj4yI91p17xfH5MiCy5wLz6nd1EZX/8zJ2gBg+b1HnqA3MHG/VSXysnug7htQXoC5wkMOUqJJvWBCO0xqeI7cGZR+p0hCrwZR9WA=
